# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: private

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    git fetch origin '+refs/heads/*:refs/heads/*'
    git checkout $(Build.SourceBranchName)
    git reset --hard $(Build.SourceBranchName)
    git pull
    git branch
    
  displayName: 'Set valid branch name'

- task: PowerShell@2
  displayName: 'Run main build script'
  inputs:
    targetType: 'filePath'
    filePath: ./src/build/bl.ps1 
    arguments: '-buildCounter $(Build.BuildId)'



- script: | 
    echo '$(System.DefaultWorkingDirectory)'
    echo '$(Build.ArtifactStagingDirectory)'
    echo '$(Agent.BuildDirectory)'
    echo '$(Build.SourcesDirectory)'
    echo '$(Build.BinariesDirectory)'
  displayName: 'Run a one-line script'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '**/Syrup.Tests.xml' 
    #searchFolder: './build/tmp/build/Syrup.Tests' # Optional
    #mergeTestResults: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/_artifacts' # Optional
    contents: '**\zip\**' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    #cleanTargetFolder: false # Optional
    #overWrite: false # Optional
    #flattenFolders: false # Optional

