# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: private

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: git checkout --progress --force $(Build.SourceBranchName)
  displayName: 'Set valid branch name'

- task: PowerShell@2
  inputs:
    displayName: 'Run main build script'
    targetType: 'filePath'
    filePath: ./src/build/bl.ps1 
    arguments: '-buildCounter $(Build.BuildId)'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'